export const colors = {
  "primary": "#ff0",
  "primaryFocus": "#dbdb00",
  "primaryContent": "#333",
  "secondary": "#0f00ff",
  "secondaryFocus": "#0d00db",
  "secondaryContent": "#fff",
  "accent": "#f00",
  "accentFocus": "#db0000",
  "accentContent": "#fff",
  "neutral": "#0a1a93",
  "neutralFocus": "#081472",
  "neutralContent": "#fff",
  "base-100": "#e6e6e6",
  "base-200": "#d4d4d4",
  "base-300": "#c2c2c2",
  "baseContent": "#333",
  "info": "#0ee",
  "infoContent": "#fff",
  "success": "#008000",
  "successContent": "#fff",
  "warning": "#fa0",
  "warningContent": "#fff",
  "error": "#f00",
  "errorContent": "#fff",
};

export const variables = {
  "--rounded-box": "",
  "--rounded-btn": "",
  "--rounded-badge": "",
  "--animation-btn": "",
  "--animation-input": "",
  "--btn-text-case": "",
  "--btn-focus-scale": "",
  "--border-btn": "",
  "--tab-border": "",
  "--tab-radius": "",
};
