export const colors = {
  "primary": "#ff0",
  "primaryFocus": "#dbdb00",
  "primaryContent": "#333",
  "secondary": "#0f00ff",
  "secondaryFocus": "#0d00db",
  "secondaryContent": "#fff",
  "accent": "#f00",
  "accentFocus": "#db0000",
  "accentContent": "#fff",
  "neutral": "#0a1a93",
  "neutralFocus": "#081472",
  "neutralContent": "#fff",
  "base-50": "#fafafa",
  "base-100": "#e6e6e6",
  "base-200": "#d2d2d2",
  "base-300": "#bebebe",
  "base-400": "#aaaaaa",
  "baseContent": "#333",
  "info": "#0ee",
  "infoContent": "#333",
  "success": "#008000",
  "successContent": "#fff",
  "warning": "#fa0",
  "warningContent": "#fff",
  "error": "#f00",
  "errorContent": "#fff",
};

export const variables = {
  "--rounded-box": "1rem",
  "--rounded-btn": "0",
  "--rounded-badge": "1.9rem",
  "--animation-btn": "0",
  "--animation-input": ".2s",
  "--shadow-btn": "1px 1px 1px 1px hsl(var(--b4))",
  "--btn-text-case": "normal",
  "--btn-focus-scale": "0.95",
  "--border-btn": "1px",
  "--tab-border": "1px",
  "--tab-radius": "0.5rem",
};
