export type ColorName = keyof typeof colorNames;

export const colorNames = {
  "primary": "--p",
  "primaryFocus": "--pf",
  "primaryContent": "--pc",
  "secondary": "--s",
  "secondaryFocus": "--sf",
  "secondaryContent": "--sc",
  "accent": "--a",
  "accentFocus": "--af",
  "accentContent": "--ac",
  "neutral": "--n",
  "neutralFocus": "--nf",
  "neutralContent": "--nc",
  "base-50": "--b50",
  "base-100": "--b1",
  "base-200": "--b2",
  "base-300": "--b3",
  "base-400": "--b4",
  "baseContent": "--bc",
  "info": "--in",
  "infoContent": "--inc",
  "success": "--su",
  "successContent": "--suc",
  "warning": "--wa",
  "warningContent": "--wac",
  "error": "--er",
  "errorContent": "--erc",
};

